# -*- coding: utf-8 -*-
from slides import MAG  # 🔴 uma cor so: duas copias do hex divergem calado
M = lambda t: f'<b style="color:{MAG}">{t}</b>'

COMT = {"slug":"comt-1709","slides":[
 {"soco":"Empolga<br>e desiste", "fundo":"capa","eyebrow":"nutrigenética na prática",
  "titulo":f'Você tem aquele paciente que {M("se empolga na segunda e desiste na quarta")}?',
  "sub":"Já investigou o gene da COMT?"},
 {"fundo":"branco","eyebrow":"você já viu os dois",
  "titulo":"Mesmo plano. Adesão oposta.",
  "corpo":["Uma abraça o protocolo inteiro, cumpre tudo por três dias e some.",
           "Outra executa igual um relógio, mas trava em qualquer imprevisto e aí desanda tudo."]},
 {"fundo":"tiff","eyebrow":"o que é",
  "titulo":"COMT, catecol-O-metiltransferase",
  "corpo":["Em ciência: a enzima que degrada dopamina, noradrenalina e adrenalina no córtex pré-frontal.",
           f'Na prática? É o {M("ralo da dopamina")}. Tem ralo largo e ralo estreito, e o mesmo estímulo enche um e transborda o outro.']},
 {"fundo":"branco","eyebrow":"rs4680",
  "titulo":"Por que a conduta inverte",
  "corpo":[f'{M("GG")} rápida, ralo largo. Dopamina pré-frontal mais baixa em repouso. Sustenta bem a pressão e precisa de recompensa perto.',
           f'{M("AA")} lenta, ralo estreito. Foco fino, e desempenho que cai quando o estresse sobe.',
           f'{M("AG")} no meio, e é o mais comum. É quem responde bem a ajuste fino.'],
  "fonte":"Humińska-Lisowska, Int J Mol Sci 2024 (revisão). Buscado no PubMed."},
 {"fundo":"branco","eyebrow":"no seu plano",
  "titulo":"O que muda",
  "corpo":[f'{M("AA")} cuidado com excesso de estímulo. Cafeína concentrada e tirosina alta viram irritabilidade. Metildoador se titula, não entra em dose cheia.',
           f'{M("GG")} suporte à síntese: ferro adequado, B6, vitamina C como cofator, e metas curtas com devolutiva frequente.',
           "Genótipo é contexto, não receita."]},
 {"fundo":"tiff","eyebrow":"duas pontas",
  "titulo":"O que quase ninguém liga",
  "corpo":["<b>Estrogênio.</b> A mesma enzima metila os estrogênios catecóis na fase 2. Numa paciente AA isso aparece no quadro hormonal, não no capítulo de humor.",
           "<b>Ferro no cérebro.</b> Em 208 adultos acompanhados, os GG mais velhos acumularam mais ferro no estriado e no pré-frontal, com pior memória de trabalho."],
  "fonte":"Gustavsson et al., Front Hum Neurosci 2022. doi 10.3389/fnhum.2022.838228"},
 {"fundo":"cta","corpo":["Você ajusta a conduta pelo COMT?",
   "Salva, que esse é pra voltar antes da próxima devolutiva.",
   "Conta nos comentários como você conduz o AA."],
  "arroba":"@scannerdasaude"}]}

IL6 = {"slug":"il6-1909","slides":[
 {"soco":"Exame normal,<br>corpo cansado", "fundo":"capa","eyebrow":"o cansaço que não aparece",
  "titulo":f'Você vive cansada, o corpo pesado, e os exames {M("não deram nada")}?',
  "sub":"O seu DNA pode explicar. Vem comigo."},
 {"fundo":"branco","eyebrow":"você reconhece isso?",
  "corpo":["Acorda cansada mesmo depois de dormir.","Sente o corpo pesado, as juntas rígidas de manhã.",
           "Incha à toa, e some e volta sem explicação.",
           "E dizem que está tudo bem, porque nos exames de rotina está mesmo."]},
 {"fundo":"tiff","eyebrow":"o que é",
  "titulo":"IL-6, interleucina 6",
  "corpo":["Em ciência: uma citocina que o corpo usa pra avisar que tem algo pra resolver.",
           f'Na prática? É o {M("alarme do corpo")}. Alarme é bom. O problema é quando ele toca baixinho o dia inteiro e você se acostuma.']},
 {"fundo":"branco","eyebrow":"o detalhe que vira o jogo",
  "titulo":"O mesmo alarme também constrói",
  "corpo":["A IL-6 sobe quando você treina, e ali ela é aliada. O músculo funciona como órgão endócrino e libera essas mensageiras na contração.",
           "A diferença está entre o pico que sobe e desce, e o murmúrio que nunca desliga."],
  "fonte":"Iglesias, J Clin Med 2025 (revisão). doi 10.3390/jcm14134490"},
 {"fundo":"branco","eyebrow":"a investigação",
  "titulo":"Eu não trato o cansaço isolado",
  "corpo":["<b>No exame:</b> PCR ultrassensível, ferritina, homocisteína, que a rotina não costuma pedir.",
           "<b>Na microbiota:</b> a barreira intestinal, que quando afrouxa mantém o alarme ligado.",
           "<b>No estilo de vida:</b> sono curto e estresse crônico sustentam o mesmo murmúrio.",
           "<b>Na genética:</b> variações na própria IL-6 mudam o quanto o seu corpo produz dela."]},
 {"fundo":"tiff","eyebrow":"no prato",
  "titulo":"As combinações, não os alimentos soltos",
  "corpo":["<b>Cúrcuma + pimenta-preta + gordura boa.</b> A piperina aumenta muito a absorção da curcumina, que sozinha quase não entra.",
           "<b>Brócolis no vapor curto + mostarda crua por cima.</b> A enzima da mostarda reativa o sulforafano que o cozimento longo destrói.",
           "<b>Azeite extravirgem sobre o prato pronto.</b> Os polifenóis se perdem no calor alto: ele é tempero, não óleo de fritura."]},
 {"fundo":"cta","corpo":["Conhece alguém que vive ouvindo que está tudo bem? Marca essa pessoa.",
   "Salva pra ler com calma.",
   "Quer investigar a SUA história? Eu sou a Detetive da Saúde."],
  "arroba":"@nutri_secrets"}]}

LAUDO = {"slug":"laudo-conduta-2409","slides":[
 {"soco":"O laudo chegou.<br>E agora?", "fundo":"capa","eyebrow":"do laudo à conduta",
  "titulo":f'Você já pediu teste nutrigenético e {M("ficou perdida")} na hora de aplicar a conduta?',
  "sub":"O laudo diz o gene. Quem diz a dose é você."},
 {"fundo":"branco","eyebrow":"o problema real",
  "titulo":"O laudo não é o difícil. O difícil é o depois.",
  "corpo":["Chega uma lista de genes com setinha pra cima e pra baixo.",
           "Qual entra na prescrição desta consulta, qual é contexto, e qual você guarda pra daqui a seis meses?"]},
 {"fundo":"tiff","eyebrow":"passo 1",
  "titulo":"A classificação vem do genótipo",
  "corpo":["O mesmo genótipo significa coisas opostas em variantes diferentes do mesmo gene. O par de alelos é o que classifica.",
           "Se o laudo não trouxe o genótipo, você não tem classificação: tem uma palavra."]},
 {"fundo":"branco","eyebrow":"passo 2",
  "titulo":"O gene sozinho não vira conduta",
  "corpo":["Gene, exame e questionário. A conduta nasce do encontro das três fontes.",
           "Gene alterado com exame normal e sem sintoma é vigilância. Com exame alterado e queixa, é prioridade desta consulta."]},
 {"fundo":"branco","eyebrow":"passo 3",
  "titulo":"São três portas, não uma",
  "corpo":["<b>Reposição:</b> o exame mostra deficiência e você repõe em dose que corrige de verdade.",
           "<b>Modulação:</b> não há deficiência, mas a via pede suporte. Homocisteína alta com B12 normal é o exemplo clássico.",
           "<b>Sintomática:</b> não há exame, há queixa e uma via que a explica.",
           "Quem só usa a primeira porta prescreve menos do que o caso precisa."]},
 {"fundo":"tiff","eyebrow":"passo 4",
  "titulo":"A fórmula se agrupa por classe",
  "corpo":["Lipossolúveis com gordura, em cápsula oleosa. Hidrossolúveis à parte. Zinco longe de ferro e cálcio. Magnésio nunca junto da D3.",
           "Probiótico sempre manipulado, todas as cepas na mesma cápsula, antes de dormir.",
           f'{M("Agrupamento errado é dose certa que não chega.")}']},
 {"fundo":"branco","eyebrow":"o que nunca muda",
  "titulo":"Processo funcional, sempre",
  "corpo":["Nutricionista não estabelece diagnóstico. Quando o exame aponta algo além do nosso escopo, a conduta é sinalizar, contextualizar e encaminhar.",
           "Isso não enfraquece a devolutiva. É o que faz o médico querer trabalhar com você."]},
 {"fundo":"cta","corpo":["Quer ver os quatro passos num caso real, do laudo à prescrição?",
   "Salva pra usar antes da próxima devolutiva.",
   "Em qual dos quatro você trava? Comenta o número."],
  "arroba":"@scannerdasaude"}]}

TODOS = [COMT, IL6, LAUDO]
